# Generated by Django 4.2.16 on 2024-10-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartHotelService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("image", models.URLField(default="", verbose_name="Фото")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        default="There is no detail text", verbose_name="Подробности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Апартамент",
                "verbose_name_plural": "Апартаменты",
                "db_table": "aparthotel_service",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания заявки",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "complete_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата приезда"
                    ),
                ),
                (
                    "final_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата выезда"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("deleted", "Удалена"),
                            ("created", "Сформирована"),
                            ("completed", "Завершёна"),
                            ("rejected", "Отклонёна"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="заявки_создателя",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="заявки_модератора",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="ApplicationApartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comments_wishes",
                    models.TextField(
                        default="Введите текст", verbose_name="Комментарии"
                    ),
                ),
                (
                    "aparthotel_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Услуга",
                        to="apartments.aparthotelservice",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Заявка",
                        to="apartments.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга в апарт-отеле",
                "verbose_name_plural": "Услуги в апарт-отеле",
                "db_table": "application_apart_service",
            },
        ),
        migrations.AddConstraint(
            model_name="applicationapartments",
            constraint=models.UniqueConstraint(
                fields=("application", "aparthotel_service"),
                name="unique_app_apartments",
            ),
        ),
    ]
