# Generated by Django 4.2.16 on 2024-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aparthotelservice",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Действует"), (2, "Удалена")],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
