# Generated by Django 4.2.16 on 2024-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0003_alter_aparthotelservice_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aparthotelservice",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото"
            ),
        ),
    ]
