# Generated by Django 4.2.16 on 2024-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0004_alter_aparthotelservice_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aparthotelservice",
            name="image",
            field=models.URLField(
                blank=True, default="", null=True, verbose_name="Фото"
            ),
        ),
    ]
